/**************************************************************
* This file is part of the project 'Studierstube' at berliOS. *
* Copyright (c) 2005-2009 Stefan Holzmüller (twelwan@gmx.de)  *
* The software and its sources are available under the terms  *
* of the (3-clause) BSD license. See LICENSE.txt for details. *
**************************************************************/

/*
 * MainViewFrame.java
 *
 * Created on Jun 9, 2009, 9:11:13 PM
 */

package studierstube.gui;

/**
 *
 * @author twel
 */
public class MainViewFrame extends javax.swing.JFrame {

    /** Creates new form MainViewFrame */
    public MainViewFrame() {
        initComponents();
        mainPanel.add(new ManageSpellsViewPanel(), "ManageZauber");
    }

    public void setStatusText(String status) {
        labelStatus.setText(status);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelStatus = new javax.swing.JPanel();
        separatorStatus = new javax.swing.JSeparator();
        labelStatus = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProgram = new javax.swing.JMenu();
        menuProgramSave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        menuProgramQuit = new javax.swing.JMenuItem();
        menuManage = new javax.swing.JMenu();
        menuManageZauber = new javax.swing.JRadioButtonMenuItem();
        menuTools = new javax.swing.JMenu();
        menuInfo = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelStatus.setText("Starting up ...");

        javax.swing.GroupLayout panelStatusLayout = new javax.swing.GroupLayout(panelStatus);
        panelStatus.setLayout(panelStatusLayout);
        panelStatusLayout.setHorizontalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separatorStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
            .addGroup(panelStatusLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(labelStatus)
                .addContainerGap(503, Short.MAX_VALUE))
        );
        panelStatusLayout.setVerticalGroup(
            panelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatusLayout.createSequentialGroup()
                .addComponent(separatorStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(labelStatus)
                .addContainerGap(3, Short.MAX_VALUE))
        );

        mainPanel.setLayout(new java.awt.CardLayout());

        menuProgram.setText("Programm");

        menuProgramSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuProgramSave.setText("Speichern");
        menuProgramSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProgramSaveActionPerformed(evt);
            }
        });
        menuProgram.add(menuProgramSave);
        menuProgram.add(jSeparator1);

        menuProgramQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        menuProgramQuit.setText("Beenden");
        menuProgramQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProgramQuitActionPerformed(evt);
            }
        });
        menuProgram.add(menuProgramQuit);

        jMenuBar1.add(menuProgram);

        menuManage.setText("Verwalten");

        menuManageZauber.setSelected(true);
        menuManageZauber.setText("Zauber");
        menuManageZauber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManageZauberActionPerformed(evt);
            }
        });
        menuManage.add(menuManageZauber);

        jMenuBar1.add(menuManage);

        menuTools.setText("Tools");
        jMenuBar1.add(menuTools);

        menuInfo.setText("Info");
        jMenuBar1.add(menuInfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuProgramQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProgramQuitActionPerformed
        studierstube.Core.shutdown();
    }//GEN-LAST:event_menuProgramQuitActionPerformed

    private void menuManageZauberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManageZauberActionPerformed

    }//GEN-LAST:event_menuManageZauberActionPerformed

    private void menuProgramSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProgramSaveActionPerformed
        studierstube.model.Spell.saveXml();  // refactor: model.AbstractModel...
    }//GEN-LAST:event_menuProgramSaveActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainViewFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenu menuInfo;
    private javax.swing.JMenu menuManage;
    private javax.swing.JRadioButtonMenuItem menuManageZauber;
    private javax.swing.JMenu menuProgram;
    private javax.swing.JMenuItem menuProgramQuit;
    private javax.swing.JMenuItem menuProgramSave;
    private javax.swing.JMenu menuTools;
    private javax.swing.JPanel panelStatus;
    private javax.swing.JSeparator separatorStatus;
    // End of variables declaration//GEN-END:variables

}
